workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      android_sdk: 34
      java: 17
    scripts:
      - name: Build Android Debug APK
        script: |
          gradle assembleDebug --stacktrace --no-daemon
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - tomidhusen43@gmail.com
        notify:
          success: true
          failure: false
